'use client';
import { useState } from 'react';
import { Badge, Button, cn } from '@fluxa/ui';
import type { Agent, Conversation, WorkflowStep } from '@fluxa/shared';
import { StepPluginPanel } from './step-plugin-panel';
import { ManualControls } from './manual-controls';
interface InboxProps { initialConversations: Conversation[]; initialAgents: Agent[]; error: string | null; }
const workflowSteps: WorkflowStep[] = ['triagem', 'cartoes', 'fatura', 'avaliação'].map((id) => ({ id, name: id, transitions: [] }));
export function Inbox({ initialConversations, initialAgents, error }: InboxProps) {
  const [conversations, setConversations] = useState(initialConversations); const [selectedId, setSelectedId] = useState(initialConversations[0]?.id ?? null);
  const selected = conversations.find((item) => item.id === selectedId); const transition = (toStepId: string) => selected && setConversations((items) => items.map((item) => item.id === selected.id ? { ...item, current_step_id: toStepId } : item));
  return <div className="flex h-screen flex-col"><header className="flex items-center justify-between border-b px-4 py-3"><div><h1 className="text-lg font-semibold">Fluxa</h1><p className="text-xs text-muted-foreground">Painel do atendente</p></div><Badge variant="success">{initialAgents.filter((agent) => agent.status === 'online').length} online</Badge></header>{error && <div className="bg-destructive/10 px-4 py-2 text-sm text-destructive">{error}</div>}<div className="grid min-h-0 flex-1 grid-cols-[260px_1fr_380px] divide-x"><aside className="overflow-y-auto">{conversations.map((conversation) => <button key={conversation.id} type="button" onClick={() => setSelectedId(conversation.id)} className={cn('w-full border-b p-3 text-left hover:bg-accent', selectedId === conversation.id && 'bg-accent')}><div className="flex justify-between"><span className="font-medium">{conversation.customer_ref}</span><Badge variant="outline">{conversation.queue_status}</Badge></div><span className="text-xs text-muted-foreground">{conversation.channel}</span></button>)}</aside>{selected ? <main className="flex min-w-0 flex-col"><header className="border-b p-4"><h2 className="font-semibold">{selected.customer_ref}</h2><p className="text-xs text-muted-foreground">Conversa {selected.id}</p></header><div className="flex-1 p-4 text-sm text-muted-foreground">Mensagens serão carregadas via API.</div><form className="flex gap-2 border-t p-3" onSubmit={(event) => event.preventDefault()}><input className="flex-1 rounded border px-3 py-2" placeholder="Responder…" /><Button>Enviar</Button></form><ManualControls steps={workflowSteps.map((step) => String(step.id))} currentStepId={selected.current_step_id} onTransition={transition} /></main> : <main className="p-4">Selecione uma conversa.</main>}{selected && <StepPluginPanel conversation={selected} currentStep={workflowSteps.find((step) => step.id === selected.current_step_id) ?? workflowSteps[0]!} onTransition={transition} />}</div></div>;
}
